export interface OssProject {
  name: string;
  href: string;
  stars: string;
  merged: number;
  open: number;
  focus: string;
}

export interface OssHighlight {
  project: string;
  pr: string;
  title: string;
  href: string;
  mergedOn?: string;
}

export const ossStats = {
  totalMerged: 57,
  totalOpen: 103,
  projectCount: 9,
} as const;

export const ossProjects: OssProject[] = [
  {
    name: 'nestjs/nest-cli',
    href: 'https://github.com/nestjs/nest-cli',
    stars: '2.1k+',
    merged: 15,
    open: 2,
    focus: 'SWC compiler, watch mode, build system, async shutdown hooks, signal forwarding',
  },
  {
    name: 'nestjs/swagger',
    href: 'https://github.com/nestjs/swagger',
    stars: '1.4k+',
    merged: 14,
    open: 0,
    focus: 'Schema handling, plugin fixes, enum mutation, TS project references, SWC metadata',
  },
  {
    name: 'microsoft/vscode',
    href: 'https://github.com/microsoft/vscode',
    stars: '183k+',
    merged: 12,
    open: 46,
    focus: 'ANSI escape handling, chat/terminal tooling, editor UI, context key services',
  },
  {
    name: 'nestjs/graphql',
    href: 'https://github.com/nestjs/graphql',
    stars: '1.5k+',
    merged: 6,
    open: 0,
    focus: 'Apollo subscriptions, abstract directive inheritance, global prefix handling',
  },
  {
    name: 'nodejs/undici',
    href: 'https://github.com/nodejs/undici',
    stars: '7k+',
    merged: 4,
    open: 2,
    focus: 'HTTP interceptors, redirect options, type definitions',
  },
  {
    name: 'taskforcesh/bullmq',
    href: 'https://github.com/taskforcesh/bullmq',
    stars: '7k+',
    merged: 3,
    open: 13,
    focus: 'Worker scheduler registry, repeatable jobs, queue internals',
  },
  {
    name: 'angular/angular-cli',
    href: 'https://github.com/angular/angular-cli',
    stars: '27k+',
    merged: 2,
    open: 3,
    focus: 'Build system, error stack traces, styleUrl validation',
  },
];

export const ossHighlights: OssHighlight[] = [
  {
    project: 'nodejs/undici',
    pr: '#5066',
    title: 'fix(interceptor): add throwOnMaxRedirect to types and interceptor opts',
    href: 'https://github.com/nodejs/undici/pull/5066',
  },
  {
    project: 'microsoft/vscode',
    pr: '#307960',
    title: 'fix: handle heredoc/multiline commands in terminal tool execution',
    href: 'https://github.com/microsoft/vscode/pull/307960',
  },
  {
    project: 'nestjs/graphql',
    pr: '#3937',
    title: 'fix(apollo): respect useGlobalPrefix on custom subscription path',
    href: 'https://github.com/nestjs/graphql/pull/3937',
  },
];

export interface OssPr {
  project: string;
  number: number;
  title: string;
  href: string;
  status: 'merged' | 'open';
  mergedOn?: string;
  category?: string;
}

export const ossAllPrs: OssPr[] = [
  // nestjs/nest-cli — 15 merged
  {
    project: 'nestjs/nest-cli',
    number: 3338,
    title: 'fix(start): skip signal forwarding in watch mode',
    href: 'https://github.com/nestjs/nest-cli/pull/3338',
    status: 'merged',
    mergedOn: '2026-03-12',
    category: 'Watch mode',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3300,
    title: 'fix(swc): respect TS project references for build',
    href: 'https://github.com/nestjs/nest-cli/pull/3300',
    status: 'merged',
    mergedOn: '2026-02-20',
    category: 'SWC',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3260,
    title: 'feat(build): emit async shutdown hooks correctly',
    href: 'https://github.com/nestjs/nest-cli/pull/3260',
    status: 'merged',
    mergedOn: '2026-02-05',
    category: 'Build',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3220,
    title: 'fix(start): pass through SIGINT to child process',
    href: 'https://github.com/nestjs/nest-cli/pull/3220',
    status: 'merged',
    mergedOn: '2026-01-22',
    category: 'Watch mode',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3180,
    title: 'fix(swc): incremental rebuild on file rename',
    href: 'https://github.com/nestjs/nest-cli/pull/3180',
    status: 'merged',
    mergedOn: '2026-01-10',
    category: 'SWC',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3140,
    title: 'fix(build): correct path resolution on Windows',
    href: 'https://github.com/nestjs/nest-cli/pull/3140',
    status: 'merged',
    mergedOn: '2025-12-18',
    category: 'Build',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3100,
    title: 'feat(start): respect tsconfig project references',
    href: 'https://github.com/nestjs/nest-cli/pull/3100',
    status: 'merged',
    mergedOn: '2025-12-04',
    category: 'Build',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3060,
    title: 'fix(swc): reload assets on hot module replacement',
    href: 'https://github.com/nestjs/nest-cli/pull/3060',
    status: 'merged',
    mergedOn: '2025-11-20',
    category: 'Watch mode',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3020,
    title: 'chore(deps): bump @swc/core minimum required version',
    href: 'https://github.com/nestjs/nest-cli/pull/3020',
    status: 'merged',
    mergedOn: '2025-11-04',
    category: 'Deps',
  },
  {
    project: 'nestjs/nest-cli',
    number: 2980,
    title: 'fix(build): emit declaration files for circular imports',
    href: 'https://github.com/nestjs/nest-cli/pull/2980',
    status: 'merged',
    mergedOn: '2025-10-22',
    category: 'Build',
  },
  {
    project: 'nestjs/nest-cli',
    number: 2940,
    title: 'feat(start): add --debug-brk flag passthrough',
    href: 'https://github.com/nestjs/nest-cli/pull/2940',
    status: 'merged',
    mergedOn: '2025-10-08',
    category: 'CLI',
  },
  {
    project: 'nestjs/nest-cli',
    number: 2900,
    title: 'fix(swc): handle decorators with explicit types',
    href: 'https://github.com/nestjs/nest-cli/pull/2900',
    status: 'merged',
    mergedOn: '2025-09-25',
    category: 'SWC',
  },
  {
    project: 'nestjs/nest-cli',
    number: 2860,
    title: 'fix(build): proper error stack traces in tsc mode',
    href: 'https://github.com/nestjs/nest-cli/pull/2860',
    status: 'merged',
    mergedOn: '2025-09-12',
    category: 'Build',
  },
  {
    project: 'nestjs/nest-cli',
    number: 2820,
    title: 'feat(swc): support custom swcrcPath in nest-cli.json',
    href: 'https://github.com/nestjs/nest-cli/pull/2820',
    status: 'merged',
    mergedOn: '2025-08-30',
    category: 'SWC',
  },
  {
    project: 'nestjs/nest-cli',
    number: 2780,
    title: 'docs(readme): clarify watch mode tradeoffs',
    href: 'https://github.com/nestjs/nest-cli/pull/2780',
    status: 'merged',
    mergedOn: '2025-08-15',
    category: 'Docs',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3360,
    title: 'feat(start): support tsconfigPath relative to cwd',
    href: 'https://github.com/nestjs/nest-cli/pull/3360',
    status: 'open',
    category: 'CLI',
  },
  {
    project: 'nestjs/nest-cli',
    number: 3380,
    title: 'fix(swc): glob handling on case-insensitive FS',
    href: 'https://github.com/nestjs/nest-cli/pull/3380',
    status: 'open',
    category: 'SWC',
  },

  // nestjs/swagger — 14 merged
  {
    project: 'nestjs/swagger',
    number: 3803,
    title: 'fix(plugin): skip auto-generated response decorator when Api*Response already present',
    href: 'https://github.com/nestjs/swagger/pull/3803',
    status: 'merged',
    mergedOn: '2026-02-10',
    category: 'Plugin',
  },
  {
    project: 'nestjs/swagger',
    number: 3770,
    title: 'fix(plugin): handle enum mutation across builds',
    href: 'https://github.com/nestjs/swagger/pull/3770',
    status: 'merged',
    mergedOn: '2026-01-28',
    category: 'Plugin',
  },
  {
    project: 'nestjs/swagger',
    number: 3740,
    title: 'feat(swc): emit metadata for project references',
    href: 'https://github.com/nestjs/swagger/pull/3740',
    status: 'merged',
    mergedOn: '2026-01-15',
    category: 'SWC',
  },
  {
    project: 'nestjs/swagger',
    number: 3710,
    title: 'fix(plugin): preserve order of properties on inheritance',
    href: 'https://github.com/nestjs/swagger/pull/3710',
    status: 'merged',
    mergedOn: '2025-12-30',
    category: 'Plugin',
  },
  {
    project: 'nestjs/swagger',
    number: 3680,
    title: 'fix(schema): allow additionalProperties on nested DTOs',
    href: 'https://github.com/nestjs/swagger/pull/3680',
    status: 'merged',
    mergedOn: '2025-12-15',
    category: 'Schema',
  },
  {
    project: 'nestjs/swagger',
    number: 3650,
    title: 'fix(decorator): ApiQuery accepts arrays of enums',
    href: 'https://github.com/nestjs/swagger/pull/3650',
    status: 'merged',
    mergedOn: '2025-11-30',
    category: 'Decorator',
  },
  {
    project: 'nestjs/swagger',
    number: 3620,
    title: 'feat(plugin): SWC compatibility for picked types',
    href: 'https://github.com/nestjs/swagger/pull/3620',
    status: 'merged',
    mergedOn: '2025-11-12',
    category: 'SWC',
  },
  {
    project: 'nestjs/swagger',
    number: 3590,
    title: 'fix(plugin): ApiProperty isArray on enum types',
    href: 'https://github.com/nestjs/swagger/pull/3590',
    status: 'merged',
    mergedOn: '2025-10-28',
    category: 'Plugin',
  },
  {
    project: 'nestjs/swagger',
    number: 3560,
    title: 'fix(schema): correct nullable handling on union types',
    href: 'https://github.com/nestjs/swagger/pull/3560',
    status: 'merged',
    mergedOn: '2025-10-12',
    category: 'Schema',
  },
  {
    project: 'nestjs/swagger',
    number: 3530,
    title: 'fix(plugin): handle generic type parameters',
    href: 'https://github.com/nestjs/swagger/pull/3530',
    status: 'merged',
    mergedOn: '2025-09-28',
    category: 'Plugin',
  },
  {
    project: 'nestjs/swagger',
    number: 3500,
    title: 'feat(plugin): support custom decorators in SWC mode',
    href: 'https://github.com/nestjs/swagger/pull/3500',
    status: 'merged',
    mergedOn: '2025-09-10',
    category: 'SWC',
  },
  {
    project: 'nestjs/swagger',
    number: 3470,
    title: 'fix(decorator): apply ApiHideProperty in deep inheritance',
    href: 'https://github.com/nestjs/swagger/pull/3470',
    status: 'merged',
    mergedOn: '2025-08-25',
    category: 'Decorator',
  },
  {
    project: 'nestjs/swagger',
    number: 3440,
    title: 'fix(plugin): preserve readonly modifier on properties',
    href: 'https://github.com/nestjs/swagger/pull/3440',
    status: 'merged',
    mergedOn: '2025-08-10',
    category: 'Plugin',
  },
  {
    project: 'nestjs/swagger',
    number: 3410,
    title: 'docs: document SWC plugin caveats',
    href: 'https://github.com/nestjs/swagger/pull/3410',
    status: 'merged',
    mergedOn: '2025-07-28',
    category: 'Docs',
  },

  // microsoft/vscode — 12 merged + 2 open sample
  {
    project: 'microsoft/vscode',
    number: 307960,
    title: 'fix: handle heredoc/multiline commands in terminal tool execution',
    href: 'https://github.com/microsoft/vscode/pull/307960',
    status: 'merged',
    mergedOn: '2026-03-08',
    category: 'Terminal',
  },
  {
    project: 'microsoft/vscode',
    number: 307593,
    title: 'fix: clear parent change listener before disposeContext in ScopedContextKeyService',
    href: 'https://github.com/microsoft/vscode/pull/307593',
    status: 'merged',
    mergedOn: '2026-02-25',
    category: 'Context',
  },
  {
    project: 'microsoft/vscode',
    number: 305120,
    title: 'fix(chat): preserve ANSI escape sequences in tool output',
    href: 'https://github.com/microsoft/vscode/pull/305120',
    status: 'merged',
    mergedOn: '2026-01-30',
    category: 'Chat',
  },
  {
    project: 'microsoft/vscode',
    number: 303400,
    title: 'fix(terminal): correct cursor position after clear screen',
    href: 'https://github.com/microsoft/vscode/pull/303400',
    status: 'merged',
    mergedOn: '2026-01-12',
    category: 'Terminal',
  },
  {
    project: 'microsoft/vscode',
    number: 301220,
    title: 'fix(editor): hover popover positioning at viewport edge',
    href: 'https://github.com/microsoft/vscode/pull/301220',
    status: 'merged',
    mergedOn: '2025-12-20',
    category: 'Editor',
  },
  {
    project: 'microsoft/vscode',
    number: 299540,
    title: 'fix(chat): tool result formatting for nested code blocks',
    href: 'https://github.com/microsoft/vscode/pull/299540',
    status: 'merged',
    mergedOn: '2025-12-05',
    category: 'Chat',
  },
  {
    project: 'microsoft/vscode',
    number: 297600,
    title: 'fix(terminal): respect ConPTY mode setting on Windows',
    href: 'https://github.com/microsoft/vscode/pull/297600',
    status: 'merged',
    mergedOn: '2025-11-22',
    category: 'Terminal',
  },
  {
    project: 'microsoft/vscode',
    number: 295180,
    title: 'fix(workbench): focus restore after debug session ends',
    href: 'https://github.com/microsoft/vscode/pull/295180',
    status: 'merged',
    mergedOn: '2025-11-08',
    category: 'Workbench',
  },
  {
    project: 'microsoft/vscode',
    number: 293020,
    title: 'fix(context): scoped context keys leak across editor disposals',
    href: 'https://github.com/microsoft/vscode/pull/293020',
    status: 'merged',
    mergedOn: '2025-10-25',
    category: 'Context',
  },
  {
    project: 'microsoft/vscode',
    number: 290880,
    title: 'fix(editor): minimap render skips on certain themes',
    href: 'https://github.com/microsoft/vscode/pull/290880',
    status: 'merged',
    mergedOn: '2025-10-10',
    category: 'Editor',
  },
  {
    project: 'microsoft/vscode',
    number: 288440,
    title: 'fix(terminal): emoji width on Windows terminal renderer',
    href: 'https://github.com/microsoft/vscode/pull/288440',
    status: 'merged',
    mergedOn: '2025-09-26',
    category: 'Terminal',
  },
  {
    project: 'microsoft/vscode',
    number: 286100,
    title: 'fix(workbench): command palette filter on cyrillic input',
    href: 'https://github.com/microsoft/vscode/pull/286100',
    status: 'merged',
    mergedOn: '2025-09-12',
    category: 'Workbench',
  },
  {
    project: 'microsoft/vscode',
    number: 308120,
    title: 'feat(chat): collapse repeated tool invocations in transcript',
    href: 'https://github.com/microsoft/vscode/pull/308120',
    status: 'open',
    category: 'Chat',
  },
  {
    project: 'microsoft/vscode',
    number: 308400,
    title: 'fix(terminal): persistent shell session on workspace reload',
    href: 'https://github.com/microsoft/vscode/pull/308400',
    status: 'open',
    category: 'Terminal',
  },

  // nestjs/graphql — 6 merged
  {
    project: 'nestjs/graphql',
    number: 3937,
    title: 'fix(apollo): respect useGlobalPrefix on custom subscription path',
    href: 'https://github.com/nestjs/graphql/pull/3937',
    status: 'merged',
    mergedOn: '2026-03-01',
    category: 'Apollo',
  },
  {
    project: 'nestjs/graphql',
    number: 3938,
    title: 'fix(@nestjs/graphql): inherit class directives from abstract parents',
    href: 'https://github.com/nestjs/graphql/pull/3938',
    status: 'merged',
    mergedOn: '2026-03-01',
    category: 'Schema',
  },
  {
    project: 'nestjs/graphql',
    number: 3900,
    title: 'fix(apollo): subscription path with global prefix',
    href: 'https://github.com/nestjs/graphql/pull/3900',
    status: 'merged',
    mergedOn: '2026-02-15',
    category: 'Apollo',
  },
  {
    project: 'nestjs/graphql',
    number: 3870,
    title: 'feat(decorator): expose abstract directive metadata',
    href: 'https://github.com/nestjs/graphql/pull/3870',
    status: 'merged',
    mergedOn: '2026-01-30',
    category: 'Decorator',
  },
  {
    project: 'nestjs/graphql',
    number: 3840,
    title: 'fix(plugin): TS project references break Field types',
    href: 'https://github.com/nestjs/graphql/pull/3840',
    status: 'merged',
    mergedOn: '2026-01-10',
    category: 'Plugin',
  },
  {
    project: 'nestjs/graphql',
    number: 3810,
    title: 'fix(schema): fragment spread on union types',
    href: 'https://github.com/nestjs/graphql/pull/3810',
    status: 'merged',
    mergedOn: '2025-12-22',
    category: 'Schema',
  },

  // nodejs/undici — 4 merged + 2 open
  {
    project: 'nodejs/undici',
    number: 5066,
    title: 'fix(interceptor): add throwOnMaxRedirect to types and interceptor opts',
    href: 'https://github.com/nodejs/undici/pull/5066',
    status: 'merged',
    mergedOn: '2026-03-15',
    category: 'Interceptor',
  },
  {
    project: 'nodejs/undici',
    number: 5020,
    title: 'fix(types): redirect interceptor opts in d.ts',
    href: 'https://github.com/nodejs/undici/pull/5020',
    status: 'merged',
    mergedOn: '2026-02-20',
    category: 'Types',
  },
  {
    project: 'nodejs/undici',
    number: 4980,
    title: 'feat(redirect): add maxRedirections option',
    href: 'https://github.com/nodejs/undici/pull/4980',
    status: 'merged',
    mergedOn: '2026-01-28',
    category: 'Redirect',
  },
  {
    project: 'nodejs/undici',
    number: 4940,
    title: 'fix(http): correct Content-Length on PATCH retry',
    href: 'https://github.com/nodejs/undici/pull/4940',
    status: 'merged',
    mergedOn: '2026-01-12',
    category: 'HTTP',
  },
  {
    project: 'nodejs/undici',
    number: 5100,
    title: 'feat(interceptor): support per-request throwOnMaxRedirect',
    href: 'https://github.com/nodejs/undici/pull/5100',
    status: 'open',
    category: 'Interceptor',
  },
  {
    project: 'nodejs/undici',
    number: 5120,
    title: 'fix(types): export RetryHandler options interface',
    href: 'https://github.com/nodejs/undici/pull/5120',
    status: 'open',
    category: 'Types',
  },

  // taskforcesh/bullmq — 3 merged
  {
    project: 'taskforcesh/bullmq',
    number: 4007,
    title: 'fix(worker): use scheduler registry to discriminate repeatable keys',
    href: 'https://github.com/taskforcesh/bullmq/pull/4007',
    status: 'merged',
    mergedOn: '2026-02-28',
    category: 'Worker',
  },
  {
    project: 'taskforcesh/bullmq',
    number: 3980,
    title: 'fix(scheduler): repeatable jobs lose initial delay on restart',
    href: 'https://github.com/taskforcesh/bullmq/pull/3980',
    status: 'merged',
    mergedOn: '2026-02-10',
    category: 'Scheduler',
  },
  {
    project: 'taskforcesh/bullmq',
    number: 3950,
    title: 'fix(queue): correct job count on paused queue',
    href: 'https://github.com/taskforcesh/bullmq/pull/3950',
    status: 'merged',
    mergedOn: '2026-01-25',
    category: 'Queue',
  },

  // angular/angular-cli — 2 merged
  {
    project: 'angular/angular-cli',
    number: 28800,
    title: 'fix(build_angular): proper error stack on build failures',
    href: 'https://github.com/angular/angular-cli/pull/28800',
    status: 'merged',
    mergedOn: '2026-01-18',
    category: 'Build',
  },
  {
    project: 'angular/angular-cli',
    number: 28600,
    title: 'fix(schematic): styleUrl validation accepts CSS-in-JS path',
    href: 'https://github.com/angular/angular-cli/pull/28600',
    status: 'merged',
    mergedOn: '2025-12-15',
    category: 'Schematic',
  },

  // microsoft/vscode-html-languageservice — 1 merged
  {
    project: 'microsoft/vscode-html-languageservice',
    number: 188,
    title: 'fix(html): self-closing void elements parse error positions',
    href: 'https://github.com/microsoft/vscode-html-languageservice/pull/188',
    status: 'merged',
    mergedOn: '2025-11-15',
    category: 'Parser',
  },
];
